site_name: HawkCD
pages:
- Resources: "resources.md"
- User Guide: "user-guide.md"
- Contribute:
    - 'Contribution Agreement': 'contribute/contribution-agreement.md'
    - 'Technical Documentation':
      - 'Software Requirements Specification': 'contribute/technical-documentation/srs.md'
      - 'Software Design Document': 'contribute/technical-documentation/sdd.md'
      - 'Hawk API': 'contribute/technical-documentation/rest-api.md'
    - 'Development Process' : 'contribute/development-process.md'
    - 'Discussions': 'contribute/discussions.md'
- Roadmap: 'roadmap.md'
- Download: 'download.md'
theme: united
#site_dir: ../../hawk-docs/hawk
