site_name: HawkCD
pages:
#- Resources: "resources.md"
- Home: "index.md"
- User Guide:
   - Concepts: "concepts/index.md"
   - Installation: "installation/index.md"
   - Configuration: "configuration/index.md"
   - Use Cases: "use-cases/index.md"
- About:
  - Release Notes: "about/release-notes.md"
  - License: "about/license.md"
theme: readthedocs
#site_dir: ../../hawk-docs/hawk
